---
include:
  - board: nice_nano_v2
    shield: lily58_left
    snippet: studio-rpc-usb-uart
    snippet: studio-rpc-ble
    cmake-args: CONFIG_ZMK_STUDIO=y

  - board: nice_nano_v2
    shield: lily58_right

  - board: nice_nano_v2
    shield: settings_reset
